server.port=8085
spring.application.name=payment-service
spring.datasource.url=jdbc:mysql://localhost:3306/edulearn_payment?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Jaiho@@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
app.jwt.secret=ZWR1bGVhcm5TZWNyZXRLZXlGb3JKV1QyMDI0UHJvZHVjdGlvblVzZU9ubHk=
app.jwt.expiration-ms=86400000
app.enrollment-service.url=http://localhost:8084
management.endpoints.web.exposure.include=health,info
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.edulearn=DEBUG
